# Generated by Django 2.1.5 on 2019-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - Not Rated '), (1, 'G - General Audiences'), (2, 'PG - Parental Guidance'), (3, 'R - Restricted')], default=0),
        ),
    ]
